/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Main.java to edit this template
 */
package GuestDashboard;

import java.awt.Color;
import java.awt.EventQueue;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.WindowConstants;

/**
 *
 * @author RD
 */
public class Rrrrr {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        new guet().setVisible(true);
        // TODO code application logic here
    }

    /**
     *
     * @author RD
     */
    public static class register extends JFrame {

        private static final Logger logger = Logger.getLogger(register.class.getName());

        /**
         * Creates new form register
         */
        public register() {
            initComponents();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings(value = "unchecked")
        private void initComponents() {
            jPanel1 = new JPanel();
            jLabel1 = new JLabel();
            registername = new JTextField();
            phonenumber = new JTextField();
            jCheckBox1 = new JCheckBox();
            jCheckBox2 = new JCheckBox();
            jLabel2 = new JLabel();
            jLabel3 = new JLabel();
            jLabel4 = new JLabel();
            DONE = new JButton();
            log_out = new JButton();
            setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
            jLabel1.setFont(new Font("Sylfaen", 1, 18)); // NOI18N
            jLabel1.setText("Program Register");
            registername.setFont(new Font("Sylfaen", 0, 18)); // NOI18N
            registername.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent evt) {
                    registernameActionPerformed(evt);
                }
            });
            phonenumber.setFont(new Font("Sylfaen", 0, 18)); // NOI18N
            phonenumber.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent evt) {
                    phonenumberActionPerformed(evt);
                }
            });
            jCheckBox1.setFont(new Font("Sylfaen", 0, 18)); // NOI18N
            jCheckBox1.setText("Diabetes management program");
            jCheckBox2.setFont(new Font("Sylfaen", 0, 18)); // NOI18N
            jCheckBox2.setText("Mental Health Support Program");
            jLabel2.setFont(new Font("Sylfaen", 0, 18)); // NOI18N
            jLabel2.setText("Enter Phone Number:");
            jLabel3.setFont(new Font("Sylfaen", 0, 18)); // NOI18N
            jLabel3.setText("Enter name:");
            jLabel4.setFont(new Font("Sylfaen", 0, 18)); // NOI18N
            jLabel4.setText("Which program(s) would you like to participate in");
            DONE.setFont(new Font("Sylfaen", 0, 18)); // NOI18N
            DONE.setText("DONE");
            DONE.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent evt) {
                    DONEActionPerformed(evt);
                }
            });
            log_out.setBackground(new Color(255, 0, 51));
            log_out.setFont(new Font("Sylfaen", 0, 14)); // NOI18N
            log_out.setText("LOG OUT");
            GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup().addGap(0, 201, Short.MAX_VALUE).addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 418, GroupLayout.PREFERRED_SIZE).addGap(196, 196, 196)).addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel1Layout.createSequentialGroup().addGap(239, 239, 239).addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(jCheckBox2, GroupLayout.PREFERRED_SIZE, 288, GroupLayout.PREFERRED_SIZE).addComponent(jCheckBox1, GroupLayout.PREFERRED_SIZE, 288, GroupLayout.PREFERRED_SIZE))).addGroup(jPanel1Layout.createSequentialGroup().addGap(312, 312, 312).addComponent(DONE, GroupLayout.PREFERRED_SIZE, 164, GroupLayout.PREFERRED_SIZE))).addGap(0, 0, Short.MAX_VALUE)).addGroup(jPanel1Layout.createSequentialGroup().addGap(252, 252, 252).addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel1Layout.createSequentialGroup().addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 191, GroupLayout.PREFERRED_SIZE).addGap(0, 0, Short.MAX_VALUE)).addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false).addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 163, GroupLayout.PREFERRED_SIZE).addComponent(registername, GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE).addComponent(phonenumber).addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 163, GroupLayout.PREFERRED_SIZE)).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(log_out))))).addContainerGap()));
            jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(jPanel1Layout.createSequentialGroup().addGap(27, 27, 27).addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 38, GroupLayout.PREFERRED_SIZE)).addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addComponent(log_out))).addGap(50, 50, 50).addComponent(jLabel3).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(registername, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE).addGap(71, 71, 71).addComponent(jLabel2).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(phonenumber, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE).addGap(20, 20, 20).addComponent(jLabel4).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(jCheckBox1).addGap(26, 26, 26).addComponent(jCheckBox2).addGap(18, 18, 18).addComponent(DONE, GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE).addContainerGap()));
            GroupLayout layout = new GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
            layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
            pack();
        } // </editor-fold>//GEN-END:initComponents

        private void registernameActionPerformed(ActionEvent evt) {
            //GEN-FIRST:event_registernameActionPerformed
            // TODO add your handling code here:
        } //GEN-LAST:event_registernameActionPerformed

        private void phonenumberActionPerformed(ActionEvent evt) {
            //GEN-FIRST:event_phonenumberActionPerformed
            // TODO add your handling code here:
        } //GEN-LAST:event_phonenumberActionPerformed

        private void DONEActionPerformed(ActionEvent evt) {
            //GEN-FIRST:event_DONEActionPerformed
            requestpending myMain = new requestpending();
            myMain.setVisible(true);
            myMain.setLocationRelativeTo(null);
            this.hide();
            // TODO add your handling code here:
        } //GEN-LAST:event_DONEActionPerformed

        /**
         * @param args the command line arguments
         */
        public static void main(String[] args) {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
             * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
             */
            try {
                for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ReflectiveOperationException | UnsupportedLookAndFeelException ex) {
                logger.log(Level.SEVERE, null, ex);
            }
            //</editor-fold>
            /* Create and display the form */
            EventQueue.invokeLater(() -> new register().setVisible(true));
        }
        // Variables declaration - do not modify//GEN-BEGIN:variables
        private JButton DONE;
        private JCheckBox jCheckBox1;
        private JCheckBox jCheckBox2;
        private JLabel jLabel1;
        private JLabel jLabel2;
        private JLabel jLabel3;
        private JLabel jLabel4;
        private JPanel jPanel1;
        private JButton log_out;
        private JTextField phonenumber;
        private JTextField registername;
        // End of variables declaration//GEN-END:variables
    }
    
}
